"""Restricted randomization: blocked factorials and split-plot designs.

Two situations stop you from running a factorial in one completely random
order, and each needs its own design *and* its own analysis.

Blocking
--------

The runs do not fit in one homogeneous batch: two days, four raw-material
lots, eight furnace loads. :func:`blocked_factorial_design` splits a 2-level
full factorial into ``n_blocks`` blocks by *confounding* chosen interactions
with blocks: every run in a block has the same sign on each block generator,
so the block effect is estimated and removed at the cost of those
interactions. The default generators are chosen by a minimum-aberration search
(confound the highest-order interactions possible, never a main effect), and
``partial_confounding=True`` confounds a *different* interaction in each
replicate so that every interaction is estimable from some replicate.

Analyse with :func:`discopt.doe.anova_report`, passing the ``block`` column as
a factor and leaving the confounded interactions out of the model (they are
aliased with blocks, and ``anova_report`` refuses them).

Split-plot
----------

Some factors are hard to change (a furnace temperature, a reactor charge), so
they are set once per *whole plot* while the easy-to-change factors vary
within it. :func:`split_plot_design` builds that two-layer randomization, and
:func:`split_plot_anova` gives each effect the error term that matches the unit
it was applied to: whole-plot factors are tested against the variation between
whole plots, and sub-plot factors (and their interactions with whole-plot
factors) against the variation within them. Analysing a split-plot as if it
were completely randomized pools the two errors, so whole-plot effects look far
more significant than they are, and sub-plot effects less.

The analysis is the classical stratum decomposition for balanced data, whose
variance-component estimates coincide with REML when both are positive.
"""

from __future__ import annotations

import itertools
import random
import warnings
from dataclasses import dataclass, field
from typing import Any, Mapping, Sequence, cast

import numpy as np

from discopt.doe.anova import AnovaEffect

__all__ = [
    "BlockedFactorialDesign",
    "SplitPlotAnovaTable",
    "SplitPlotDesign",
    "blocked_factorial_design",
    "split_plot_anova",
    "split_plot_design",
]


# ---------------------------------------------------------------------------
# Words (interactions) as bitmasks over the factor list
# ---------------------------------------------------------------------------


def _popcount(a: np.ndarray) -> np.ndarray:
    a = a.astype(np.int64)
    out = np.zeros_like(a)
    while np.any(a):
        out += a & 1
        a = a >> 1
    return out


def _word_name(mask: int, names: Sequence[str]) -> str:
    return ":".join(n for i, n in enumerate(names) if mask >> i & 1)


def _parse_word(word: Any, names: Sequence[str]) -> int:
    """Accept ``("A", "B")``, ``"A:B"``, ``"A*B"``, or ``"AB"`` (single-letter names)."""
    if isinstance(word, str):
        if ":" in word or "*" in word:
            parts = [p.strip() for p in word.replace("*", ":").split(":") if p.strip()]
        elif word in names:
            parts = [word]
        elif all(len(n) == 1 for n in names):
            parts = list(word)
        else:
            raise ValueError(
                f"cannot parse block generator {word!r}: join multi-character factor "
                "names with ':' (e.g. 'temp:time:cat') or pass a tuple of names"
            )
    else:
        parts = list(word)
    mask = 0
    for p in parts:
        if p not in names:
            raise ValueError(f"block generator {word!r}: unknown factor {p!r}")
        mask ^= 1 << names.index(p)
    if mask == 0:
        raise ValueError(f"block generator {word!r} is empty")
    return mask


def _span(gens: Sequence[int]) -> list[int]:
    words: set[int] = set()
    for r in range(1, len(gens) + 1):
        for combo in itertools.combinations(gens, r):
            w = 0
            for g in combo:
                w ^= g
            words.add(w)
    return sorted(words)


def _candidate_subgroups(k: int, p: int) -> np.ndarray:
    """Every set of confounded words (the nonzero elements of a p-dim subgroup
    generated by p independent words), as rows of an int array, with no word of
    length 1 (a main effect may never be confounded with blocks)."""
    words = np.arange(1, 2**k, dtype=np.int64)
    words = words[_popcount(words) >= 2]
    if p == 1:
        return words.reshape(-1, 1)
    if p == 2:
        a, b = np.meshgrid(words, words, indexing="ij")
        a, b = a.ravel(), b.ravel()
        c = a ^ b
        keep = (a < b) & (b < c) & (_popcount(c) >= 2)
        return np.stack([a[keep], b[keep], c[keep]], axis=1)
    if p == 3:
        pairs = _candidate_subgroups(k, 2)
        out = []
        for c in words:
            span = np.column_stack(
                [pairs, np.full(len(pairs), c), pairs[:, 0] ^ c, pairs[:, 1] ^ c, pairs[:, 2] ^ c]
            )
            keep = (c > pairs[:, 2]) & np.all(_popcount(span) >= 2, axis=1)
            out.append(span[keep].astype(np.int16))
        return np.concatenate(out) if out else np.zeros((0, 7), dtype=np.int16)
    raise ValueError("automatic block generators support up to 8 blocks; pass block_generators")


def _aberration_order(cands: np.ndarray, k: int) -> np.ndarray:
    """Indices of ``cands`` sorted by minimum aberration (fewest short words first)."""
    lengths = _popcount(cands)
    counts = np.stack([(lengths == L).sum(axis=1) for L in range(2, k + 1)], axis=1)
    # np.lexsort sorts by the *last* key first; we want length-2 counts first.
    return np.lexsort(counts.T[::-1])


# ---------------------------------------------------------------------------
# Blocked factorials
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class BlockedFactorialDesign:
    """A 2-level full factorial run in blocks.

    Attributes
    ----------
    factors, low, high : tuple
        Factor names and their two levels, as in :class:`FactorialDesign`.
    n_blocks : int
        Blocks per replicate.
    generators : tuple of tuple of str
        The block generators used in each replicate (``"A:B:C"`` form).
    confounded_effects : tuple of tuple of str
        For each replicate, every interaction confounded with blocks: the
        generators and all their products. With ``partial_confounding`` these
        differ between replicates.
    rows : list of dict
        One dict per run: the factor values, ``block`` (1-based and unique
        across replicates, since blocks in different replicates are different
        physical batches), ``replicate`` (0-based), ``is_center``, and
        ``run_order`` (blocks in sequence, runs randomized within each block).
    """

    factors: tuple[str, ...]
    low: tuple[object, ...]
    high: tuple[object, ...]
    n_blocks: int
    generators: tuple[tuple[str, ...], ...]
    confounded_effects: tuple[tuple[str, ...], ...]
    rows: list[dict[str, object]]

    def __len__(self) -> int:
        return len(self.rows)


def blocked_factorial_design(
    factors: Mapping[str, tuple[object, object]],
    *,
    n_blocks: int,
    block_generators: Sequence[Any] | Sequence[Sequence[Any]] | None = None,
    replicates: int = 1,
    partial_confounding: bool = False,
    center_points_per_block: int = 0,
    seed: int | None = None,
) -> BlockedFactorialDesign:
    """Split a randomized 2-level full factorial into blocks.

    Parameters
    ----------
    factors : mapping name -> (low, high)
        Two levels per factor, numeric or categorical (2 -- 8 factors).
    n_blocks : int
        Blocks per replicate: a power of two, at most ``2**(k-1)``.
    block_generators : sequence, optional
        ``log2(n_blocks)`` independent interactions to confound with blocks,
        each as a tuple of factor names, ``"A:B:C"``, or ``"ABC"`` when every
        name is a single letter. Their products are confounded too. Omit to
        use a minimum-aberration choice (automatic for up to 8 blocks). With
        ``partial_confounding=True`` pass one such sequence per replicate.
    replicates : int, default 1
        Replicates of the whole blocked design; each gets its own blocks.
    partial_confounding : bool, default False
        Confound different interactions in different replicates, so that every
        interaction is unconfounded in at least one replicate (needs
        ``replicates >= 2``). Chosen greedily: each replicate takes the
        minimum-aberration generators that overlap least with what earlier
        replicates already confounded.
    center_points_per_block : int, default 0
        Centre runs added to every block (numeric factors only). They give a
        pure-error estimate and a curvature check within each block.
    seed : int, optional
        Reproducible randomization.

    Returns
    -------
    BlockedFactorialDesign
    """
    if not factors:
        raise ValueError("at least one factor required")
    names = tuple(factors.keys())
    k = len(names)
    if k < 2 or k > 8:
        raise ValueError(f"blocked factorials support 2 -- 8 factors, got {k}")
    if replicates < 1:
        raise ValueError(f"replicates must be >= 1, got {replicates}")
    if center_points_per_block < 0:
        raise ValueError("center_points_per_block must be >= 0")
    p = int(round(np.log2(n_blocks))) if n_blocks >= 1 else -1
    if n_blocks < 2 or 2**p != n_blocks:
        raise ValueError(f"n_blocks must be a power of two >= 2, got {n_blocks}")
    if p > k - 1:
        raise ValueError(f"{k} factors allow at most {2 ** (k - 1)} blocks, got {n_blocks}")
    if partial_confounding and replicates < 2:
        raise ValueError("partial_confounding needs replicates >= 2")

    lows = tuple(factors[n][0] for n in names)
    highs = tuple(factors[n][1] for n in names)
    for n, lo, hi in zip(names, lows, highs):
        if lo == hi:
            raise ValueError(f"factor {n!r}: low and high levels must differ")
    numeric = all(_is_numeric(v) for v in lows + highs)
    if center_points_per_block and not numeric:
        raise ValueError("center_points_per_block > 0 requires all factors to be numeric")

    # Generators per replicate, as bitmasks.
    per_rep: list[list[int]] = []
    if block_generators is not None:
        if partial_confounding:
            sets = list(block_generators)
            if len(sets) != replicates:
                raise ValueError(
                    "with partial_confounding, pass one generator set per replicate "
                    f"({replicates}), got {len(sets)}"
                )
        else:
            sets = [block_generators] * replicates
        for gens in sets:
            masks = [_parse_word(g, names) for g in gens]
            if len(masks) != p:
                raise ValueError(
                    f"{n_blocks} blocks need {p} independent generators, got {len(masks)}"
                )
            span = _span(masks)
            if len(span) != 2**p - 1:
                raise ValueError("block generators are not independent")
            mains = [_word_name(w, names) for w in span if bin(w).count("1") == 1]
            if mains:
                raise ValueError(
                    f"these generators confound main effect(s) {mains} with blocks; "
                    "choose higher-order interactions"
                )
            per_rep.append(masks)
    else:
        cands = _candidate_subgroups(k, p)
        order = _aberration_order(cands, k)
        cands = cands[order]
        confounded_so_far: set[int] = set()
        for _ in range(replicates):
            if partial_confounding and confounded_so_far:
                overlap = np.isin(cands, list(confounded_so_far)).sum(axis=1)
                idx = int(np.argmin(overlap))  # stable: best aberration among least overlap
            else:
                idx = 0
            chosen = [int(w) for w in cands[idx]]
            per_rep.append(_basis(chosen, p))
            confounded_so_far |= set(chosen)
            if not partial_confounding:
                per_rep = per_rep * replicates
                break

    rng = random.Random(seed)
    rows: list[dict[str, object]] = []
    corners = list(itertools.product((0, 1), repeat=k))
    block_offset = 0
    for r, gens in enumerate(per_rep):
        blocks: dict[int, list[dict[str, object]]] = {b: [] for b in range(n_blocks)}
        for code in corners:
            b = 0
            for j, g in enumerate(gens):
                sign = 1
                for i in range(k):
                    if g >> i & 1 and not code[i]:
                        sign = -sign
                if sign > 0:
                    b |= 1 << j
            row: dict[str, object] = {names[i]: highs[i] if code[i] else lows[i] for i in range(k)}
            row["is_center"] = False
            blocks[b].append(row)
        for b in range(n_blocks):
            for _ in range(center_points_per_block):
                cp: dict[str, object] = {
                    names[i]: (float(cast(float, lows[i])) + float(cast(float, highs[i]))) / 2.0
                    for i in range(k)
                }
                cp["is_center"] = True
                blocks[b].append(cp)
        block_order = list(range(n_blocks))
        rng.shuffle(block_order)
        for label, b in enumerate(block_order, start=1):
            members = blocks[b]
            rng.shuffle(members)
            for row in members:
                row["block"] = block_offset + label
                row["replicate"] = r
                rows.append(row)
        block_offset += n_blocks
    for i, row in enumerate(rows):
        row["run_order"] = i

    return BlockedFactorialDesign(
        factors=names,
        low=lows,
        high=highs,
        n_blocks=n_blocks,
        generators=tuple(tuple(_word_name(g, names) for g in gens) for gens in per_rep),
        confounded_effects=tuple(
            tuple(
                _word_name(w, names)
                for w in sorted(_span(gens), key=lambda w: (bin(w).count("1"), w))
            )
            for gens in per_rep
        ),
        rows=rows,
    )


def _basis(words: Sequence[int], p: int) -> list[int]:
    """``p`` independent words spanning the given subgroup elements."""
    basis: list[int] = []
    for w in words:
        if len(basis) == p:
            break
        if not basis or w not in _span(basis):
            basis.append(w)
    return basis


def _ordered_levels(values) -> list[object]:
    """Distinct levels, numeric ones in numeric order (so the second is "high")."""
    uniq = list(dict.fromkeys(values))
    if all(_is_numeric(v) for v in uniq):
        return sorted(uniq, key=lambda v: float(cast(float, v)))
    return sorted(uniq, key=str)


def _is_numeric(v: object) -> bool:
    return isinstance(v, (int, float)) and not isinstance(v, bool)


# ---------------------------------------------------------------------------
# Split-plot designs
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SplitPlotDesign:
    """A randomized split-plot design.

    Attributes
    ----------
    whole_plot_factors, sub_plot_factors : tuple of str
        Hard-to-change factors (set once per whole plot) and easy-to-change
        factors (varied within each whole plot).
    levels : dict
        ``name -> (low, high)`` for every factor.
    n_whole_plots : int
        Number of whole plots (e.g. furnace runs).
    rows : list of dict
        One dict per run: every factor value, ``whole_plot`` (0-based, in run
        sequence), ``replicate`` (which copy of the *whole-plot* factorial this
        whole plot belongs to; not a block of the whole experiment),
        ``sub_replicate`` (which copy of the sub-plot factorial within the
        whole plot), and ``run_order``. Whole plots run in random order, and
        the sub-plot runs are randomized *within* each whole plot.
    """

    whole_plot_factors: tuple[str, ...]
    sub_plot_factors: tuple[str, ...]
    levels: dict[str, tuple[object, object]]
    n_whole_plots: int
    rows: list[dict[str, object]]

    def __len__(self) -> int:
        return len(self.rows)


def split_plot_design(
    whole_plot_factors: Mapping[str, tuple[object, object]],
    sub_plot_factors: Mapping[str, tuple[object, object]],
    *,
    whole_plot_replicates: int = 2,
    sub_plot_replicates: int = 1,
    seed: int | None = None,
) -> SplitPlotDesign:
    """Build a 2-level split-plot design.

    Every combination of the whole-plot factors is run ``whole_plot_replicates``
    times as a whole plot, and each whole plot holds the full factorial in the
    sub-plot factors ``sub_plot_replicates`` times (e.g. 16 samples in one
    furnace firing for a 2^3 sub-plot factorial run twice).

    Parameters
    ----------
    whole_plot_factors : mapping name -> (low, high)
        Hard-to-change factors. Levels may be numeric or categorical.
    sub_plot_factors : mapping name -> (low, high)
        Easy-to-change factors.
    whole_plot_replicates : int, default 2
        Whole plots per whole-plot treatment. At least 2: with one, there are
        no degrees of freedom for whole-plot error, and the whole-plot factors
        cannot be tested at all.
    sub_plot_replicates : int, default 1
        Copies of the sub-plot factorial inside each whole plot. Extra copies
        add sub-plot error degrees of freedom; they do nothing for the
        whole-plot factors, whose precision is set by the number of whole plots.
    seed : int, optional
        Reproducible randomization.
    """
    if not whole_plot_factors or not sub_plot_factors:
        raise ValueError("a split-plot needs at least one whole-plot and one sub-plot factor")
    overlap = set(whole_plot_factors) & set(sub_plot_factors)
    if overlap:
        raise ValueError(f"factors cannot be both whole-plot and sub-plot: {sorted(overlap)}")
    if whole_plot_replicates < 1:
        raise ValueError("whole_plot_replicates must be >= 1")
    if sub_plot_replicates < 1:
        raise ValueError("sub_plot_replicates must be >= 1")
    if whole_plot_replicates == 1:
        warnings.warn(
            "whole_plot_replicates=1 leaves no degrees of freedom for whole-plot "
            "error: the whole-plot factors cannot be tested",
            stacklevel=2,
        )
    levels: dict[str, tuple[object, object]] = {}
    for name, (lo, hi) in {**whole_plot_factors, **sub_plot_factors}.items():
        if lo == hi:
            raise ValueError(f"factor {name!r}: low and high levels must differ")
        levels[name] = (lo, hi)

    wp_names = tuple(whole_plot_factors)
    sp_names = tuple(sub_plot_factors)
    rng = random.Random(seed)
    whole_plots: list[dict[str, object]] = []
    for r in range(whole_plot_replicates):
        for code in itertools.product((0, 1), repeat=len(wp_names)):
            wp = {n: levels[n][c] for n, c in zip(wp_names, code)}
            wp["replicate"] = r
            whole_plots.append(wp)
    rng.shuffle(whole_plots)

    rows: list[dict[str, object]] = []
    for w, wp in enumerate(whole_plots):
        subs = [
            {**{n: levels[n][c] for n, c in zip(sp_names, code)}, "sub_replicate": s_rep}
            for s_rep in range(sub_plot_replicates)
            for code in itertools.product((0, 1), repeat=len(sp_names))
        ]
        rng.shuffle(subs)
        for sp in subs:
            rows.append(
                {
                    **{n: wp[n] for n in wp_names},
                    **sp,
                    "whole_plot": w,
                    "replicate": wp["replicate"],
                }
            )
    for i, row in enumerate(rows):
        row["run_order"] = i

    return SplitPlotDesign(
        whole_plot_factors=wp_names,
        sub_plot_factors=sp_names,
        levels=levels,
        n_whole_plots=len(whole_plots),
        rows=rows,
    )


# ---------------------------------------------------------------------------
# Split-plot analysis
# ---------------------------------------------------------------------------


@dataclass
class SplitPlotAnovaTable:
    """Two-stratum ANOVA for a balanced split-plot experiment.

    Attributes
    ----------
    rows : list of AnovaEffect
        Whole-plot terms, ``"Whole-plot error"``, sub-plot terms,
        ``"Sub-plot error"``, and ``"Total"``, in that order. Each term's F and
        p are computed against its own stratum's error.
    strata : dict
        ``term -> "whole-plot"`` or ``"sub-plot"``.
    variance_components : dict
        ``{"whole_plot": σ²_WP, "sub_plot": σ²_SP}``: the ANOVA (method-of-
        moments) estimates, equal to REML for balanced data when positive;
        a negative whole-plot estimate is truncated at 0.
    effects : list of dict
        For every term whose factors all have two levels: the signed effect
        (mean at the product-sign +1 minus mean at -1), its standard error
        from the matching stratum, degrees of freedom, t and p.
    n_obs, n_whole_plots, runs_per_whole_plot : int
    response : str
    """

    rows: list[AnovaEffect]
    strata: dict[str, str]
    variance_components: dict[str, float]
    effects: list[dict[str, Any]] = field(default_factory=list)
    n_obs: int = 0
    n_whole_plots: int = 0
    runs_per_whole_plot: int = 0
    response: str = ""

    def summary(self) -> str:
        header = f"{'Source':<22s} {'SS':>12s} {'df':>5s} {'MS':>12s} {'F':>9s} {'p':>10s}"
        lines = [header, "-" * len(header)]
        for r in self.rows:
            f_str = "      ---" if r.f is None else f"{r.f:9.3f}"
            p_str = "       ---" if r.p is None else f"{r.p:10.4g}"
            ms_str = "         ---" if r.source == "Total" or r.df == 0 else f"{r.ms:12.4f}"
            lines.append(f"{r.source:<22s} {r.ss:12.4f} {r.df:5d} {ms_str} {f_str} {p_str}")
        vc = self.variance_components
        lines.append("")
        lines.append(
            f"Variance components: whole-plot {vc['whole_plot']:.4g}, sub-plot {vc['sub_plot']:.4g}"
        )
        return "\n".join(lines)

    def __str__(self) -> str:
        return self.summary()


def _term_block(rows: Sequence[Mapping[str, object]], term: tuple[str, ...]) -> np.ndarray:
    keys = [tuple(r[f] for f in term) for r in rows]
    cells: dict[tuple[object, ...], int] = {}
    for key in keys:
        cells.setdefault(key, len(cells))
    block = np.zeros((len(rows), len(cells)))
    for i, key in enumerate(keys):
        block[i, cells[key]] = 1.0
    return block


def _sequential(
    rows: Sequence[Mapping[str, object]],
    y: np.ndarray,
    base: np.ndarray,
    terms: Sequence[tuple[str, ...]],
    levels: Mapping[str, list[object]],
) -> tuple[list[tuple[str, float, int]], float, int]:
    """Sequential SS for ``terms`` after the columns in ``base``."""
    X = base
    rank = int(np.linalg.matrix_rank(X))
    coef, *_ = np.linalg.lstsq(X, y, rcond=None)
    rss = float(np.sum((y - X @ coef) ** 2))
    out = []
    for term in terms:
        nominal = 1
        for f in term:
            nominal *= len(levels[f]) - 1
        X_new = np.hstack([X, _term_block(rows, term)])
        rank_new = int(np.linalg.matrix_rank(X_new))
        df = rank_new - rank
        if df < nominal:
            raise ValueError(
                f"term {':'.join(term)!r} is aliased: {nominal} degrees of freedom but only "
                f"{df} are estimable after the terms before it"
            )
        coef, *_ = np.linalg.lstsq(X_new, y, rcond=None)
        rss_new = float(np.sum((y - X_new @ coef) ** 2))
        out.append((":".join(term), max(rss - rss_new, 0.0), df))
        X, rank, rss = X_new, rank_new, rss_new
    return out, rss, rank


def split_plot_anova(
    rows: Sequence[Mapping[str, object]],
    response: str,
    *,
    whole_plot_factors: Sequence[str],
    sub_plot_factors: Sequence[str],
    whole_plot: str = "whole_plot",
    interactions: Sequence[Sequence[str]] | None = None,
) -> SplitPlotAnovaTable:
    """Analyse a balanced split-plot experiment with two error strata.

    Whole-plot terms (main effects of whole-plot factors, and interactions
    among them only) are tested against **whole-plot error**: the variation of
    whole-plot means about the whole-plot model. Everything else (sub-plot main
    effects and any interaction involving a sub-plot factor) is tested against
    **sub-plot error**: the residual within whole plots, with every whole plot
    as a block. Sums of squares are sequential within each stratum, in the
    order main effects, then ``interactions``.

    Parameters
    ----------
    rows : sequence of mapping
        One row per run, with the response, every factor, and the whole-plot id.
    response : str
        The response column.
    whole_plot_factors, sub_plot_factors : sequence of str
        Hard-to-change and easy-to-change factors.
    whole_plot : str, default ``"whole_plot"``
        Column identifying the whole plot each run belongs to.
    interactions : sequence of tuple of str, optional
        Interaction terms to include. Each is assigned to its stratum
        automatically.

    Returns
    -------
    SplitPlotAnovaTable

    Raises
    ------
    ValueError
        If a column is missing, a whole-plot factor varies within a whole plot,
        whole plots are unequal in size, or a term is aliased.
    """
    from scipy.stats import f as f_dist
    from scipy.stats import t as t_dist

    rows = list(rows)
    wp_f, sp_f = list(whole_plot_factors), list(sub_plot_factors)
    if not wp_f or not sp_f:
        raise ValueError("need at least one whole-plot and one sub-plot factor")
    needed = [response, whole_plot, *wp_f, *sp_f]
    missing = sorted({c for c in needed for r in rows if c not in r})
    if missing:
        raise ValueError(f"column(s) {missing} missing from some rows")
    try:
        y = np.array([float(cast(float, r[response])) for r in rows])
    except (TypeError, ValueError) as e:
        raise ValueError(f"response column {response!r} must be numeric") from e
    if not np.all(np.isfinite(y)):
        raise ValueError("response contains non-finite values")

    # Whole-plot bookkeeping and balance.
    plots: dict[object, list[int]] = {}
    for i, r in enumerate(rows):
        plots.setdefault(r[whole_plot], []).append(i)
    sizes = {len(v) for v in plots.values()}
    if len(sizes) != 1:
        raise ValueError(
            f"whole plots have unequal sizes {sorted(sizes)}; the design must be balanced"
        )
    m = sizes.pop()
    if m < 2:
        raise ValueError("each whole plot needs at least two runs")
    for f in wp_f:
        for w, idx in plots.items():
            if len({rows[i][f] for i in idx}) != 1:
                raise ValueError(
                    f"whole-plot factor {f!r} varies within whole plot {w!r}; it must be "
                    "constant within each whole plot"
                )

    levels = {f: _ordered_levels(r[f] for r in rows) for f in wp_f + sp_f}
    wp_terms: list[tuple[str, ...]] = [(f,) for f in wp_f]
    sp_terms: list[tuple[str, ...]] = [(f,) for f in sp_f]
    for inter in interactions or ():
        term = tuple(inter)
        unknown = [f for f in term if f not in levels]
        if unknown:
            raise ValueError(f"interaction {term}: unknown factor(s) {unknown}")
        (wp_terms if all(f in wp_f for f in term) else sp_terms).append(term)

    n, n_wp = len(rows), len(plots)
    grand = float(y.mean())
    ss_total = float(np.sum((y - grand) ** 2))

    # Whole-plot stratum: the whole-plot means, scaled back by m.
    plot_ids = list(plots)
    wp_rows = [rows[plots[w][0]] for w in plot_ids]
    wp_means = np.array([y[plots[w]].mean() for w in plot_ids])
    wp_results, wp_rss, wp_rank = _sequential(
        wp_rows, wp_means, np.ones((n_wp, 1)), wp_terms, levels
    )
    wp_results = [(name, m * ss, df) for name, ss, df in wp_results]
    ss_wp_err = m * wp_rss
    df_wp_err = n_wp - wp_rank

    # Sub-plot stratum: whole plots as blocks.
    plot_block = _term_block(rows, (whole_plot,))
    sp_results, sp_rss, sp_rank = _sequential(rows, y, plot_block, sp_terms, levels)
    df_sp_err = n - sp_rank
    if df_sp_err < 1:
        raise ValueError("no degrees of freedom left for sub-plot error; drop a term")

    ms_wp_err = ss_wp_err / df_wp_err if df_wp_err > 0 else float("nan")
    ms_sp_err = sp_rss / df_sp_err
    if df_wp_err == 0:
        warnings.warn(
            "no degrees of freedom for whole-plot error (one whole plot per "
            "whole-plot treatment): whole-plot factors cannot be tested",
            stacklevel=2,
        )

    def tested(name: str, ss: float, df: int, ms_err: float, df_err: int) -> AnovaEffect:
        ms = ss / df
        if df_err > 0 and ms_err > 0:
            f_stat = ms / ms_err
            return AnovaEffect(name, ss, df, ms, f_stat, float(f_dist.sf(f_stat, df, df_err)))
        return AnovaEffect(name, ss, df, ms, None, None)

    out_rows = [tested(nm, ss, df, ms_wp_err, df_wp_err) for nm, ss, df in wp_results]
    out_rows.append(AnovaEffect("Whole-plot error", ss_wp_err, df_wp_err, ms_wp_err, None, None))
    out_rows += [tested(nm, ss, df, ms_sp_err, df_sp_err) for nm, ss, df in sp_results]
    out_rows.append(AnovaEffect("Sub-plot error", sp_rss, df_sp_err, ms_sp_err, None, None))
    out_rows.append(AnovaEffect("Total", ss_total, n - 1, 0.0, None, None))

    strata = {nm: "whole-plot" for nm, _, _ in wp_results}
    strata.update({nm: "sub-plot" for nm, _, _ in sp_results})

    sigma2_wp = (ms_wp_err - ms_sp_err) / m if df_wp_err > 0 else float("nan")
    variance_components = {
        "whole_plot": max(sigma2_wp, 0.0) if np.isfinite(sigma2_wp) else float("nan"),
        "sub_plot": ms_sp_err,
    }

    # Signed effects for 2-level terms, each with its own stratum's error.
    effects = []
    for term in wp_terms + sp_terms:
        if not all(len(levels[f]) == 2 for f in term):
            continue
        sign = np.ones(n)
        for f in term:
            hi = levels[f][1]
            sign *= np.array([1.0 if r[f] == hi else -1.0 for r in rows])
        if np.sum(sign > 0) == 0 or np.sum(sign < 0) == 0:
            continue
        effect = float(y[sign > 0].mean() - y[sign < 0].mean())
        name = ":".join(term)
        stratum = strata[name]
        ms_err, df_err = (
            (ms_wp_err, df_wp_err) if stratum == "whole-plot" else (ms_sp_err, df_sp_err)
        )
        se = float(np.sqrt(4.0 * ms_err / n)) if df_err > 0 else float("nan")
        t_val = effect / se if se and np.isfinite(se) and se > 0 else float("nan")
        p_val = float(2 * t_dist.sf(abs(t_val), df_err)) if np.isfinite(t_val) else float("nan")
        effects.append(
            {
                "term": name,
                "stratum": stratum,
                "effect": effect,
                "se": se,
                "df": df_err,
                "t": t_val,
                "p": p_val,
                "high": tuple(levels[f][1] for f in term),
            }
        )

    return SplitPlotAnovaTable(
        rows=out_rows,
        strata=strata,
        variance_components=variance_components,
        effects=effects,
        n_obs=n,
        n_whole_plots=n_wp,
        runs_per_whole_plot=m,
        response=response,
    )
